### ISSUE TITLE
name clash

### ISSUE THREAD

**Issue by simonmichael** [jthacker/shelltest#1]
Hi @jthacker. Great minds think alike! I'm the author of https://github.com/simonmichael/shelltestrunner, first released in 2011, with executable named `shelltest`. I wonder how would you feel about renaming yours, to reduce confusion ?

**Comment by jthacker** [comment]
Hi @simonmichael! I don't have a problem renaming this but I have already published artifacts on pypi and have projects that depend on those releases. Thus I'm unable to remove those artifacts or rename them per the pypi constraints.  I went ahead and added a disclaimer and pointed to your project to remove the risk for confusion.
